spring:
  application:
    name: devus-config

---
spring:
  config:
    activate:
      on-profile: dev,native
  cloud:
    config:
      server:
        native:
          search-locations: file://${HOME}/dev/hst/devus/devus-be/configurations

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Team-HST/devus
          search-paths: devus-be/configurations